name: Testing IaaC Pre-Flight
on:
  # push:
    # branches: [ "main", "add-psruleforazure" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      optionfile:
        description: "The path to an options file"
        default: "ps-rule-preflight.yaml"

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Run PSRule analysis Pre-Flight
      uses: Microsoft/ps-rule@v2.9.0
      with:
        modules: PSRule.Rules.Azure,PSRule.Monitor
        conventions: Monitor.LogAnalytics.Import
        option: ${{ github.event.inputs.optionfile }}
        inputType: inputPath
        inputPath: 'modules/bicep/'
      env:
        PSRULE_CONFIGURATION_MONITOR_WORKSPACE_ID: ${{ vars.MONITOR_WORKSPACE_ID }}
        PSRULE_CONFIGURATION_MONITOR_WORKSPACE_KEY: ${{ secrets.MONITOR_WORKSPACE_KEY }}

  deploy:
    runs-on: ubuntu-latest
    needs: analyze
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        resourceGroupName: 'rg-psruleforazure'
        template: ./modules/bicep/route-table.bicep
        failOnStdErr: true