name: Testing IaaC NPROD
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
    # branches: [ "main", "add-psruleforazure" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      optionfile:
        description: "The path to an options file"
        default: "ps-rule-inflight.yaml"

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        inlineScript: |
          Get-AzContext
          Export-AzRuleData -OutputPath 'out/templates/'
          Assert-PSRule -Module 'PSRule.Rules.Azure' -InputPath 'out/templates/' -Format File -Option ${{ github.event.inputs.optionfile }}
