name: Testing IaaC In-Flight
on:
  # push:
    # branches: [ "main", "add-psruleforazure" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      optionfile:
        description: "The path to an options file"
        default: "ps-rule-inflight.yaml"

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install PSRule
      uses: Microsoft/ps-rule@v2.9.0
      with:
        modules: PsRule.Rules.Azure
        option: ${{ github.event.inputs.optionfile }}

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - name: Get arm templates from resource group
      uses: azure/powershell@v1
      with:
        inlineScript: |
          Get-AzContext
          Export-AzRuleData -ResourceGroupName 'rg-psruleforazure' -OutputPath 'out/templates/'
        azPSVersion: 'latest'

    - name: Run PSRule analysis In-Flight
      uses: Microsoft/ps-rule@v2.9.0
      with:
        modules: PSRule.Rules.Azure,PSRule.Monitor
        conventions: Monitor.LogAnalytics.Import
        option: ${{ github.event.inputs.optionfile }}
        inputType: inputPath
        inputPath: 'out/templates/*.json'
      env:
        PSRULE_CONFIGURATION_MONITOR_WORKSPACE_ID: ${{ vars.MONITOR_WORKSPACE_ID }}
        PSRULE_CONFIGURATION_MONITOR_WORKSPACE_KEY: ${{ secrets.MONITOR_WORKSPACE_KEY }}