name: Testing IaaC - In-Flight
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "add-psruleforazure" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      optionfile:
        description: "The path to an options file"
        default: "ps-rule-inflight.yaml"

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - name: Run PSRule analysis In-Flight
      uses: azure/powershell@v1
      with:
        inlineScript: |
          Install-Module -Repository PSGallery -Name PSRule -Scope CurrentUser -Force;
          Install-Module -Repository PSGallery -Name Az.Accounts -Scope CurrentUser -Force;
          Install-Module -Repository PSGallery -Name Az.Resources -Scope CurrentUser -Force;
          Get-AzContext
          Export-AzRuleData -OutputPath 'out/templates/'
          Assert-PSRule -Module 'PSRule.Rules.Azure' -InputPath 'out/templates/' -Format File -Option ${{ github.event.inputs.optionfile }}
        azPSVersion: 'latest'
