name: Testing IaaC NPROD
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main", "add-psruleforazure" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      optionfile:
        description: "The path to an options file"
        default: "ps-rule-dev.yaml"

jobs:
  analyze:
    name: Analyze repository
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Run PSRule analysis
      uses: Microsoft/ps-rule@v2.9.0
      with:
        modules: PsRule.Rules.Azure
        option: ${{ github.event.inputs.optionfile }}